scripts: add Zephyr to stop script
Signed-off-by: Todor Minchev <todor.minchev@linux.intel.com>

diff --git a/scripts/stop_containers b/scripts/stop_containers
--- a/scripts/stop_containers
+++ b/scripts/stop_containers
@@ -5,24 +5,29 @@
 #
 # Example:
 #
-# ./tests/stop_containers
+# ./scripts/stop_containers
 
 NAME_BASE="crops-toolchain-test"
 
 II=0
-Q=`docker ps | egrep ${NAME_BASE}${II} | awk '{print $1}'`
+Q=`docker ps -a | egrep ${NAME_BASE}${II} | awk '{print $1}'`
 while [ "$Q" != ""  ]; do
     echo "Stop and Remove toolchain container $II"
-    docker stop -t 1 $Q || { echo 'docker stop $Q failed' ; exit 1; };
-    docker rm $Q || { echo 'docker rm $Q failed' ; exit 1; };
+    docker rm -f $Q || { echo 'docker rm $Q failed' ; exit 1; };
     let II=$II+1
-    Q=`docker ps | egrep ${NAME_BASE}${II} | awk '{print $1}'`
+    Q=`docker ps -a | egrep ${NAME_BASE}${II} | awk '{print $1}'`
 done
+
+echo "Stop and remove Zephyr test container"
+Q=`docker ps -a | egrep zephyr-test | awk '{print $1}'`
+if [ "$Q"  != "" ]; then
+    echo "Removing Zephyr container"
+    docker rm -f $Q || { echo 'docker rm $Q failed' ; exit 1; };
+fi
 
 echo "Stop and remove CODI test container"
 Q=`docker ps -a | egrep codi-test | awk '{print $1}'`
 if [ "$Q"  != "" ]; then
     echo "Removing codi container"
-    docker stop -t 1 $Q || { echo 'docker stop $Qfailed' ; exit 1; };
-    docker rm $Q || { echo 'docker rm $Q failed' ; exit 1; };
+    docker rm -f $Q || { echo 'docker rm $Q failed' ; exit 1; };
 fi
